### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by thomas-coudrat** [jasperzuallaert/VIBFold#2]
Hi Jasper,

I've found your analysis script ([visualize_alphafold_results.py](https://github.com/jasperzuallaert/VIBFold/blob/main/visualize_alphafold_results.py)) particularly useful and would like to ensure that I respect its intended use. I notice you haven't stated a particular software license in your repo, which [defaults to a restrictive licence](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license). Did you intend for this code to be Open Source, and would you consider a permissive license such at [MIT](https://opensource.org/license/mit/)?

Cheers,

Thomas

**Comment by jasperzuallaert** [comment]
Thanks for pointing this out, Thomas. I added the MIT license to the repository. Best of luck with your AlphaFold adventures :-)

Warm regards,
Jasper
